### ISSUE TITLE
Application error: a client-side exception has occurred (developer guidance) cuando se navega con los escudos de Brave activados

### ISSUE THREAD

**Issue by VentGrey** [RangoHQ/Rango-Website#1]
El sitio carga perfectamente cuando se navega con los escudos del navegador Brave desactivados, sin embargo al activarlos, se generan dos errores de carga, ambos muy similares:

```
framework-<id>.js:1 TypeError: Cannot read property 'indexOf' of null
```

:thinking:  ¿Está mi navegador conflictuando con el código del sitio?

**Comment by oliverloops** [comment]
Parece ser que llegamos a la conclusión que me comentas sobre los escudos avanzados en Brave Browser particularmente y el fingerprinting de la animación en 3D del cubo, por ahora solo recomendaría pasar esa configuración a estándar **_Fingerprint blocked (standard_**) para no tener ese problema.

Agradezco a @VentGrey el cual me dio una gran explicación sobre las causas del bloqueo de fingerprinting de los escudos de Brave, ya que parece que cualquier interacción con el Canvas y WebGL son detectadas como maliciosas. pero no hay nada de que preocuparse en este caso.
